### ISSUE TITLE
fix background image

### ISSUE THREAD

**Issue by asagynbaev** [BermetBakyt/proficommunications.github.io#1]
@BermetBakyt  Please have a look on it. Need to fix The text is superimposed on the following block

![2023-01-10 14 13 57](https://user-images.githubusercontent.com/29392221/211496874-85770ae8-1cf1-44c3-8f0a-a7e07b978b80.jpg)

**Comment by BermetBakyt** [comment]
fixed

**Comment by BermetBakyt** [comment]
are there any places to fix, could you have a look please @asagynbaev

**Comment by asagynbaev** [comment]
Fixed #1
